apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongo-web-application
  finalizers: []
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: "https://kubernetes.default.svc"
  source:
    helm:
      valueFiles:
        - values.yaml
    repoURL: "https://github.com/LookLukeLemon/k8s-playground"
    path: mongo-web
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
